name: job-dependency-workflow

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  CODE_CLONE:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Clone Message
        run: echo "Cloning the code"

  BUILD:
    runs-on: ubuntu-latest
    needs: CODE_CLONE
    steps:
      - name: Build Code
        run: echo "Building the code"

  TEST:
    runs-on: ubuntu-latest
    needs: BUILD
    steps:
      - name: Test Code
        run: echo "Testing the code"

  DEPLOY:
    runs-on: ubuntu-latest
    needs: TEST
    steps:
      - name: Deploy Code
        run: echo "Deploying the code"
