name: Manually-Trigger-Inputs
on: 
  workflow_dispatch:   # to manually trigger the workflow we need to use workflow_dispatch event type
    inputs:   # inputs field
      environment:   # Input Name
        description: 'Deploying to Environment'    # Description for the Input
        required: true
        default: 'test'
      age:
        description: "enter the age"
        type: number
        required: true
        default: 26
      gender:
        description: "choose the gender "
        type : choice
        options:
          - Male
          - FeMale
jobs:
  demo-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo " deploying to ${{ inputs.environment}} "
      - run: echo " age of the employee is  ${{ inputs.age}} "
