name: Manually-Trigger-Inputs
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploying to Environment'
        type: string
        default: 'test'
jobs:
  demo-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo " deploying to ${{ inputs.environment}}
